print("Enter your name: ")
n = input()
n = n[0].upper() + n[1:].lower()
print("Hi " + n + ", How old are you?")
ed = input()
print("You are "+n+", and you have " + ed + " years old")
print("do you want to continue playing ? yes or not ?")
r = input()
if r=="yes":
    print("Let's play "+ n)
else:
    print("Go to sleep now")
print("Hi " + n + " , when were you born ? " )
born = input()
print("Hi " + n + " , what's your favorite animal ? " )
animal = input()
print("you are "+n)
print(ed)
print(born)
print(animal)
print("   /|")
print("  / |")
print(" /  |")
print("/___|")
